apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app: django-app
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: django-app
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: wackoobserver/test_deploy_proj:1.0
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-password
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-name
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-host