# Generated by Django 4.0.2 on 2022-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("task_id", models.CharField(max_length=100, unique=True)),
                ("is_revoked", models.BooleanField()),
            ],
        )
    ]
