# Generated by Django 3.2 on 2022-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="is_revoked",
            field=models.BooleanField(default=False),
        )
    ]
