apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000
  type: NodePort
  selector:
    app: postgres